---  
  - name: create database
    mysql_db: name=cloudstones state=present

  - name: create mysql user
    mysql_user:
           name: cloud
           password: Cloud_123
           priv: '*.*:ALL'
           #host_all: yes
           state: present
           login_user: root
           login_password: "{{mysql_root_password}}"

  - name: clone binary-code repo
    git: repo=https://github.com/krishnamaram2/binary-code.git dest=/home/centos/binary-code

  - name: import indigo.sql
    shell: mysql -u krishna -pKrishna_123 cloudstones < /home/centos/binary-code/binaries/cloudstones.sql



