---  
  - name: create database
    mysql_db: name=indigo state=present

  - name: create mysql user
    mysql_user:
           name: krishna
           password: Krishna_123
           priv: '*.*:ALL'
           state: present
           login_user: root
           login_password: "{{mysql_root_password}}"
           host: '%'

  - name: clone binary-code repo
    git: repo=https://github.com/krishnamaram2/binary-code.git dest=/home/centos/binary-code

  - name: import indigo.sql
    shell: mysql -u krishna -pKrishna_123 indigo < /home/centos/binary-code/binaries/indigo.sql



