- hosts: localhost
  become: yes
  #vars_files:
  #   - configuration-manager/src/plays/meta_data.json

  roles:
    # - {  role: ~/configuration-manager/src/webapp/roles/webserver}
    # - {  role: ~/configuration-manager/src/webapp/roles/webappserver}
    # - {  role: ~/configuration-manager/src/webapp/roles/appserver}
      - {  role: ~/configuration-manager/src/webapp/roles/krishna.mysql}
      - {  role: ~/configuration-manager/src/webapp/roles/krishna-mysql}
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   

#- hosts: localhost
#  become: yes
#  vars_files:
#     - /home/centos/meta_data.json
#  vars_files:
#    - "/home/centos/Configuration_Manager/src/plays/meta_data.yml"
# vars_files:  /home/centos/Configuration_Manager/src/plays/meta_data.txt
#  roles:
#   - {  role: /home/centos/Configuration_Manager/src/roles/webserver, when: meta.server_role == 'web' }
#   - {  role: /home/centos/Configuration_Manager/src/roles/appserver, when: vm_role == 'app' }
#   - { role: /home/centos/Configuration_Manager/src/roles/krishna.mysql, when: server_role == 'db' }
#    - { role: /home/centos/Configuration_Manager/src/roles/krishna-mysql, when: server_role == 'db' }
#      become: yes



#---
#- hosts:
  #  - all
  # become: yes
  #roles:
  #  - role : webserver










#- hosts: dbserver
#  roles:
#    - role: geerlingguy.mysql
#    - role: krishna-mysql
#      become: yes
