---
    - name: Make sure that we can connect to the machine
      ping:
    
    - name: install openjdk
      yum: name=java-1.8.0-openjdk-devel  state=present

    - name: add group "tomcat"
      group: name=tomcat

    - name: add user "tomcat"
      user: name=tomcat group=tomcat createhome=no
      become: true

    - name: ansible create directory example
      file:  path=/opt/tomcat  owner=tomcat group=tomcat state=directory mode=0777 recurse=yes
      
    - name: Download foo.conf
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz
        dest: /opt/tomcat
   
   
    - name: Extract Tomcat archive
      unarchive: src=/opt/tomcat/apache-tomcat-8.5.61.tar.gz dest=/opt/tomcat remote_src=yes

    - name: change ownership 
      file: path=/opt/tomcat/apache-tomcat-8.5.61 state=directory recurse=yes owner=centos group=centos mode=0755
 

    - name: cloning git repo
      git: repo=https://github.com/krishnamaram2/binary-code.git
           dest=/home/centos/binary-code

    - name: Stop Tomcat
      command: nohup /opt/tomcat/apache-tomcat-8.5.61/bin/shutdown.sh
      become: true
      become_user: root

    - name: deploy war file in webapps diretcory
      copy:  src=/home/centos/binary-code/binaries/Student.war dest=/opt/tomcat/apache-tomcat-8.5.61/webapps/

    - name: Start Tomcat
      command: nohup /opt/tomcat/apache-tomcat-8.5.61/bin/startup.sh
      become: true
      become_user: root
   
    - name: change ownership 
      file: path=/opt/tomcat/apache-tomcat-8.5.61/webapps/ state=directory recurse=yes owner=centos group=centos mode=0666
    - name: commenting a line in server.xml
      replace:
           path: /opt/tomcat/apache-tomcat-8.5.61/conf/server.xml
           regexp: '<Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />'
           replace: '<!-- <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />-->'


    - name: changge localhost in application.properties file
      replace:
          path: /opt/tomcat/apache-tomcat-8.5.61/webapps/Student/WEB-INF/classes/application.properties
          regexp: 'localhost'
          replace: '34.231.57.92'


    - name: Start Tomcat
      command: nohup /opt/tomcat/apache-tomcat-8.5.61/bin/startup.sh
      become: true
      become_user: root
